# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Posy-Plugin-Cache-File
version:      0.1
version_from: lib/Posy/Plugin/Cache/File.pm
installdirs:  site
requires:
    Cache::File:                   0
    Posy:                          0.97
    Posy::Core:                    0.97
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
